### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Eldenroot** [RevertIT/mybb-rt_livesearch#5] opened 2023-05-13 11:33 UTC
Please, could you add a compatibility with 7.4?

I am asking because MyBB itself is not fully compatible (yet) with PHP 8.0 and newer so I am forced to use oldder version... including some plugins...

Thank you!

I have a blank plugin page when I wanna use your plugin with lower PHP.

@RevertIT 

Thank you!

**Comment by RevertIT** [comment] 2023-05-13 17:26
Duplicate of #4

Hi, I made the plugin with a focus on getting people to transition to PHP 8 and making it future-proof.

As the plugin is open source, anyone is free to fork it and downgrade it for their needs.

**Closed** 2023-05-13 17:28 UTC
Labels: duplicate

**Comment by Eldenroot** [comment] 2023-05-13 18:04
I understand but MyBB 1.8.33 is not compatible...
